Adam Stallard Oct 2024 fixes
pluralitybook/plurality pull request #1030
Opened 2024-10-08 06:44 UTC by adamstallard

Various small fixes to the English content.

2024-10-22 19:51 UTC, GlenWeyl requested changes
These are all good, but you need to resolve conflicting branches.

2024-10-23 04:20 UTC, adamstallard commented on contents/english/3-2-connected-society.md
> +In his 1927 work that defined his political philosophy, *The Public and its Problems*, John Dewey (whom we meet in [A View from Yushan](https://www.plurality.net/v/chapters/2-1/eng/?mode=dark)) consi
I resolved the conflict on this line and merged the changes.

2024-10-23 04:22 UTC, adamstallard commented
@GlenWeyl ready for you

2024-12-11 17:45 UTC, GlenWeyl approved these changes
Great!

2024-12-11 17:46 UTC, GlenWeyl commented
Please join Gov4Git so I can credit you.

2024-12-11 17:46 UTC, merged