Identity Section Improvements
pluralitybook/plurality pull request #49
Opened 2023-07-11 18:02 UTC by Identitywoman

I at Glen's request wrote about identity systems/documents in a WEIRD historical context.

2023-07-11 18:20 UTC, pluralitybook commented
Yup!  Reviewing now.

 

From: Kaliya - Identity Woman ***@***.***> 
Sent: Tuesday, July 11, 2023 2:03 PM
To: pluralitybook/plurality ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pluralitybook/plurality] Identity Section Improvements (PR #49)

 

I at Glen's request wrote about identity systems/documents in a WEIRD historical context.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/pluralitybook/plurality/pull/49


Commit Summary


*	34f6872 <https://github.com/pluralitybook/plurality/pull/49/commits/34f6872d489d4b6b5e9e7d41b87c1d5449c4aa11>  Update LostDao.md
*	547d329 <https://github.com/pluralitybook/plurality/pull/49/commits/547d32939f5392fba99a99dc0ccec63d5f6847d4>  Update LostDao.md
*	edd4d16 <https://github.com/pluralitybook/plurality/pull/49/commits/edd4d1671c6897c6310a0f606a0d6bb4d914ab7b>  Update LostDao.md
*	1ce709d <https://github.com/pluralitybook/plurality/pull/49/commits/1ce709dbaa7dcf605f1b8bdb904d064580e3cac6>  Merge pull request #1 from Identitywoman/Identitywoman-patch-1
*	162c486 <https://github.com/pluralitybook/plurality/pull/49/commits/162c48619154c395be02e7e47c7026f1cbdc1c61>  Update LostDao.md
*	fb9f4d1 <https://github.com/pluralitybook/plurality/pull/49/commits/fb9f4d11d98de4243d0310fb08d9022ed4fb57ad>  Update LostDao.md


File Changes 


(1 <https://github.com/pluralitybook/plurality/pull/49/files>  file)

*	M LostDao.md <https://github.com/pluralitybook/plurality/pull/49/files#diff-8b176bcbc6192df561bbe29cd2fe7da484fec574651280642c90923b86a11dc6>  (194) 


Patch Links:


*	https://github.com/pluralitybook/plurality/pull/49.patch
*	https://github.com/pluralitybook/plurality/pull/49.diff

—
Reply to this email directly, view it on GitHub <https://github.com/pluralitybook/plurality/pull/49> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3BRRPQGFQ2YK63SOCC4IGLXPWINBANCNFSM6AAAAAA2GLWENQ> .
You are receiving this because you are subscribed to this thread.  <https://github.com/notifications/beacon/A3BRRPUX72BTGSXXPSXZPULXPWINBA5CNFSM6AAAAAA2GLWENSWGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHGWQPN4M.gif> Message ID: ***@***.*** ***@***.***> >

2023-07-11 18:25 UTC, pluralitybook requested changes
In general I really like what you did here.  I'd like to have more references added, but someone else can do this later, and there are parts that don't quite belong here that I will move to a different chapter.  But the biggest problem is that I think something in your editor auto-removed the indent of every paragraph in the document and I don't want to merge your PR as it will force me to redo this globally.  Could you fix this before I merge the PR?

2023-07-11 21:10 UTC, Identitywoman commented
I did that removal of the indents.
Best practice for mark down is not to have indents.

the weird characters were driving me nuts.
If you really want me to add in spaces I will.
- Kaliya


On Tue, Jul 11, 2023 at 11:26 AM pluralitybook ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> In general I really like what you did here. I'd like to have more
> references added, but someone else can do this later, and there are parts
> that don't quite belong here that I will move to a different chapter. But
> the biggest problem is that I think something in your editor auto-removed
> the indent of every paragraph in the document and I don't want to merge
> your PR as it will force me to redo this globally. Could you fix this
> before I merge the PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pluralitybook/plurality/pull/49#pullrequestreview-1524919784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW3CCYTY7BVCG5QMLMFFQDXPWLEBANCNFSM6AAAAAA2GLWENQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-11 22:06 UTC, pluralitybook commented
If you want to submit a global formatting change to all chapters, I will consider this, but it doesn’t belong in this local PR, or so bad hygiene.Infinite diversity in infinite combinationshttps://www.RadicalxChange.org.On Jul 11, 2023, at 5:10 PM, Kaliya - Identity Woman ***@***.***> wrote:﻿
I did that removal of the indents.

Best practice for mark down is not to have indents.



the weird characters were driving me nuts.

If you really want me to add in spaces I will.

- Kaliya





On Tue, Jul 11, 2023 at 11:26 AM pluralitybook ***@***.***>

wrote:



> ***@***.**** requested changes on this pull request.

>

> In general I really like what you did here. I'd like to have more

> references added, but someone else can do this later, and there are parts

> that don't quite belong here that I will move to a different chapter. But

> the biggest problem is that I think something in your editor auto-removed

> the indent of every paragraph in the document and I don't want to merge

> your PR as it will force me to redo this globally. Could you fix this

> before I merge the PR?

>

> —

> Reply to this email directly, view it on GitHub

> <https://github.com/pluralitybook/plurality/pull/49#pullrequestreview-1524919784>,

> or unsubscribe

> <https://github.com/notifications/unsubscribe-auth/AAW3CCYTY7BVCG5QMLMFFQDXPWLEBANCNFSM6AAAAAA2GLWENQ>

> .

> You are receiving this because you authored the thread.Message ID:

> ***@***.***>

>



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-07-15 13:27 UTC, audreyt commented on LostDao.md
> +Who you where and where you fit was not "obious" based on your kin relations anymore. So, as people began to move around more and new institutions formed paper based systems to document who belonged
`obious` => `obvious`

2024-02-21 20:13 UTC, closed without merging