PDF pipeline: Include endorsement at the end, and add 6-5 Learning
pluralitybook/plurality pull request #855
Opened 2024-04-08 00:53 UTC by audreyt

2024-04-08 01:16 UTC, GlenWeyl requested changes
It is more common to put endorsements as the very first thing following the cover.  I am ok with this, but consider the change @audreyt.

2024-04-09 04:29 UTC, audreyt commented
Endorsements are now at the beginning. For technical reasons, laying it out before the TOC will take much more work, so I've put it right after the credits and before part 1.

2024-04-09 09:50 UTC, GlenWeyl approved these changes

2024-04-09 09:50 UTC, GlenWeyl approved these changes
Thank you!

2024-04-09 09:51 UTC, merged