fix typo & duplicated sentences
pluralitybook/plurality pull request #994
Opened 2024-08-23 13:59 UTC by ychi

故份有限公司 -> 股份有限公司

2024-08-29 16:44 UTC, giselechou commented
Got it! and thanks. @ychi  @GlenWeyl 

@ychi 

謝謝，我直接送出另一份修改（對齊出版品段落）

財產：故份＝>股份 ok. 
投票：段落對齊華文出版品

2024-09-06 17:59 UTC, GlenWeyl commented
@giselechou please approve.

2024-09-07 15:58 UTC, giselechou requested changes
Hi @ychi Can you keep the 23 lines（故->股） of content and resend it once?

2024-09-07 16:06 UTC, giselechou approved these changes

2024-09-07 16:08 UTC, audreyt approved these changes

2024-09-07 16:08 UTC, merged